"""
init/templates.py — Workspace template skeleton data.

Defines:
    TEMPLATE_SKELETON — directory structure + file contents
        with {team_name}, {team_description}, {timestamp} placeholders.

To add a new template file, add an entry to TEMPLATE_SKELETON["files"].
To add a new directory, add to TEMPLATE_SKELETON["directories"].
Each file template supports Python ``str.format()`` for substitution.
"""

from __future__ import annotations

TEMPLATE_SKELETON: dict = {
    "directories": [
        ".open-teams",
        ".open-teams/skills",
        ".open-teams/memory",
        ".github",
        ".github/ISSUE_TEMPLATE",
        ".github/workflows",
        "docs",
        "scripts",
    ],
    "files": {
        ".open-teams/config.yaml": """\
# open-teams Workspace Configuration
# Generated by open-teams init on {timestamp}

version: "1"

template:
  name: standard
  version: "1.0.0"
  source: "https://github.com/struggling-bird/open-teams"

team:
  name: "{team_name}"
  description: "{team_description}"

skills:
  enabled: []
  disabled: []

settings:
  auto_validate: true
  backup_before_upgrade: true
  check_updates: true
""",
        ".open-teams/skills/.gitkeep": "",
        ".open-teams/memory/.gitkeep": "",
        "AGENTS.md": """\
# {team_name} — 团队 AI 工作空间

{team_description}

> 🤖 **AI 引导者指令：** 下面是团队 AI 工作空间的**起始模板**。它已经包含了一套多 Agent 协作的骨架（架构图、角色注册表、通信协议），这是 open-teams 从真实项目中沉淀下来的可复用规范。
>
> 你的任务：**通过对话了解用户的项目，帮他们把这份模板适配成自己的团队工作空间。** 永远不要让用户手动编辑文件——你来读写。
>
> 引导流程：
> 1. 先和用户聊清楚项目背景、技术栈、团队规模 → 更新下方「Agent Registry」
> 2. 确认哪些 Skills 适合他们 → 激活对应 Skill
> 3. 把团队特有的规范、红线写入本文
> 4. 写入第一条 `memory/YYYY-MM-DD.md`
>
> 原则：渐进式，自然对话，不是填表。每次会话先读本文。

---

## Team Architecture

```
                    ┌─────────────────────┐
                    │   Team Lead (协调者)  │
                    │   审查/整合/最终决策   │
                    └──────┬──────────────┘
           ┌───────────────┼───────────────────┐
           │               │                   │
    ┌──────▼──────┐ ┌─────▼──────┐    ┌───────▼───────┐
    │  开发 Agent  │ │ 文档 Agent  │    │ 运营 Agent     │
    │  (coding)   │ │  (docs)    │    │  (ops)        │
    └──────┬──────┘ └─────┬──────┘    └───────┬───────┘
           │              │                   │
    ┌──────▼──────┐ ┌─────▼──────┐    ┌───────▼───────┐
    │  审查 Agent  │ │ 设计 Agent  │    │ 社区 Agent     │
    │  (review)   │ │  (design)  │    │  (community)  │
    └─────────────┘ └────────────┘    └───────────────┘
```

> 💡 这是一个**参考架构**。你的团队可能不需要 6 个 Agent，也可能需要更多。和 AI 对话，让它帮你调整为适合你的结构。

## Agent Registry

| Agent ID | 角色 | 职责 | 输出目录 |
|----------|------|------|----------|
| coding | 开发 Agent | 代码实现、重构、Bug 修复、代码生成 | — |
| review | 审查 Agent | Code Review、安全检查、性能审计、规范检查 | — |
| docs | 文档 Agent | README、API 文档、变更日志、知识库维护 | — |
| design | 设计 Agent | 架构设计评审、技术方案评估、系统设计 | — |
| ops | 运营 Agent | CI/CD、发布管理、监控告警、环境配置 | — |
| community | 社区 Agent | Issue 管理、PR Review、社区互动、贡献者引导 | — |

> 💡 和 AI 对话，让它帮你填上每个 Agent 的实际职责和输出目录。不需要的 Agent 可以删除，不够的可以新增。

## Agent Communication Protocol

- **独立工作，集中审查：** 每个 Agent 独立完成任务，由 Team Lead（你）最终审查和整合
- **文件传递依赖：** Agent 之间的协作通过 deliverable 文件进行，不依赖实时通信
- **标准输出格式：** 所有 Agent 输出使用 Markdown + 可执行文件（如适用）
- **上下文隔离：** 每个 Agent 只加载自己需要的 Skill 上下文，避免信息过载

> 💡 这套 Protocol 可以直接用。如果你的团队有自己的协作习惯（比如用 PR 而非文件传递），让 AI 帮你改。

## 团队规范 & 红线

> 和 AI 填充以下内容：

### 技术栈
- 语言/框架：_
- 数据库：_
- 部署方式：_

### 代码规范
- 风格指南：_
- Git 工作流：_
- Commit 规范：_

### AI 工具偏好
- 主要使用的 AI 编程工具：_

### 硬性红线
- ⛔ _
- ⛔ _

---

## 工作空间信息

- **初始化时间：** {timestamp}
- **模板来源：** [open-teams](https://github.com/struggling-bird/open-teams)

---

_此文件由 AI 在对话中维护。你只需要和 AI 聊天，它来更新。_
""",
        "README.md": """\
# {team_name}

{team_description}

## Quick Start

```bash
open-teams status
open-teams new-skill my-first-skill
```

## Skills

This workspace uses open-teams skills to define automated workflows.

## License

MIT
""",
        ".github/ISSUE_TEMPLATE/bug_report.md": """\
---
name: Bug Report
about: Report a bug to help us improve
title: "[BUG] "
labels: bug
assignees: ""
---

## Description

<!-- Describe the bug -->

## Steps to Reproduce

1.
2.
3.

## Expected Behavior

## Actual Behavior

## Environment

- OS:
- open-teams version:
""",
        ".github/ISSUE_TEMPLATE/feature_request.md": """\
---
name: Feature Request
about: Suggest an idea for this project
title: "[FEATURE] "
labels: enhancement
assignees: ""
---

## Problem

<!-- What problem are you trying to solve? -->

## Proposed Solution

<!-- Describe the solution you'd like -->

## Alternatives Considered

<!-- What alternatives have you considered? -->

## Additional Context
""",
        ".github/workflows/ci.yml": """\
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate workspace
        run: |
          python3 scripts/validate_template_layout.py
""",
        ".gitignore": """\
# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
venv/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# open-teams
.open-teams/backups/
""",
        "CONTRIBUTING.md": """\
# Contributing to {team_name}

Thanks for your interest in contributing!

## How to Contribute

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Run `open-teams validate`
5. Submit a pull request

## Code Style

- Follow existing patterns
- Write docstrings for public functions
- Add tests for new functionality

## Questions?

Open an issue or start a discussion.
""",
    },
}
