"""
init/templates.py — Workspace template skeleton data.

Defines:
    TEMPLATE_SKELETON — directory structure + file contents
        with {team_name}, {team_description}, {timestamp} placeholders.

To add a new template file, add an entry to TEMPLATE_SKELETON["files"].
To add a new directory, add to TEMPLATE_SKELETON["directories"].
Each file template supports Python ``str.format()`` for substitution.
"""

from __future__ import annotations

TEMPLATE_SKELETON: dict = {
    "directories": [
        ".open-teams",
        ".open-teams/skills",
        ".open-teams/memory",
        ".github",
        ".github/ISSUE_TEMPLATE",
        ".github/workflows",
        "docs",
        "scripts",
    ],
    "files": {
        ".open-teams/config.yaml": """\
# open-teams Workspace Configuration
# Generated by open-teams init on {timestamp}

version: "1"

template:
  name: standard
  version: "1.0.0"
  source: "https://github.com/struggling-bird/open-teams"

team:
  name: "{team_name}"
  description: "{team_description}"

skills:
  enabled: []
  disabled: []

settings:
  auto_validate: true
  backup_before_upgrade: true
  check_updates: true
""",
        ".open-teams/skills/.gitkeep": "",
        ".open-teams/memory/.gitkeep": "",
        "AGENTS.md": """\
# {team_name}

{team_description}

## Workspace

This is an open-teams workspace. It was initialized on {timestamp}.

## Getting Started

- Run `open-teams status` to see workspace health
- Run `open-teams new-skill <name>` to create a new skill
- Run `open-teams validate` to check workspace integrity

## Related

- [open-teams on GitHub](https://github.com/struggling-bird/open-teams)
""",
        "README.md": """\
# {team_name}

{team_description}

## Quick Start

```bash
open-teams status
open-teams new-skill my-first-skill
```

## Skills

This workspace uses open-teams skills to define automated workflows.

## License

MIT
""",
        ".github/ISSUE_TEMPLATE/bug_report.md": """\
---
name: Bug Report
about: Report a bug to help us improve
title: "[BUG] "
labels: bug
assignees: ""
---

## Description

<!-- Describe the bug -->

## Steps to Reproduce

1.
2.
3.

## Expected Behavior

## Actual Behavior

## Environment

- OS:
- open-teams version:
""",
        ".github/ISSUE_TEMPLATE/feature_request.md": """\
---
name: Feature Request
about: Suggest an idea for this project
title: "[FEATURE] "
labels: enhancement
assignees: ""
---

## Problem

<!-- What problem are you trying to solve? -->

## Proposed Solution

<!-- Describe the solution you'd like -->

## Alternatives Considered

<!-- What alternatives have you considered? -->

## Additional Context
""",
        ".github/workflows/ci.yml": """\
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate workspace
        run: |
          python3 scripts/validate_template_layout.py
""",
        ".gitignore": """\
# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
venv/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# open-teams
.open-teams/backups/
""",
        "CONTRIBUTING.md": """\
# Contributing to {team_name}

Thanks for your interest in contributing!

## How to Contribute

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Run `open-teams validate`
5. Submit a pull request

## Code Style

- Follow existing patterns
- Write docstrings for public functions
- Add tests for new functionality

## Questions?

Open an issue or start a discussion.
""",
    },
}
